import type { ExternalSoftware } from "@/lib/marketing/pricingTypes";

const VERIFIED_AT = "2026-08-04";

export const EXTERNAL_SOFTWARE_PRICING: ExternalSoftware[] = [
  {
    id: "hubspot-sales-starter",
    name: "HubSpot Sales Hub Starter",
    category: "Ventas y clientes",
    description: "Contactos, pipeline comercial y seguimiento basico de ventas.",
    pricingType: "per-user",
    monthlyPrice: 20,
    currency: "USD",
    billingCadence: "monthly",
    billingLabel: "por usuario/mes",
    priceNote: "Precio de pago mensual mostrado en la pagina oficial.",
    officialUrl: "https://www.hubspot.com/pricing/sales",
    lastVerifiedAt: VERIFIED_AT,
    selectedByDefault: true,
    verificationStatus: "verified",
  },
  {
    id: "pipedrive-lite",
    name: "Pipedrive Lite",
    category: "Ventas y clientes",
    description: "CRM de ventas para leads, negocios, contactos y agenda comercial.",
    pricingType: "per-user",
    monthlyPrice: 14,
    annualPrice: 168,
    currency: "USD",
    billingCadence: "annual",
    billingLabel: "por usuario/mes, facturado anual",
    priceNote: "Precio anual oficial dividido por mes para estimacion mensual.",
    officialUrl: "https://www.pipedrive.com/en/pricing",
    lastVerifiedAt: VERIFIED_AT,
    verificationStatus: "verified",
  },
  {
    id: "zoho-crm-standard",
    name: "Zoho CRM Standard",
    category: "Ventas y clientes",
    description: "CRM para oportunidades, automatizaciones iniciales y reportes comerciales.",
    pricingType: "per-user",
    monthlyPrice: 14,
    annualPrice: 168,
    currency: "USD",
    billingCadence: "annual",
    billingLabel: "por usuario/mes, facturado anual",
    priceNote: "Precio USD mostrado por la calculadora oficial de Zoho CRM.",
    officialUrl: "https://www.zoho.com/crm/zohocrm-pricing-calculator.html",
    lastVerifiedAt: VERIFIED_AT,
    verificationStatus: "verified",
  },
  {
    id: "asana-starter",
    name: "Asana Starter",
    category: "Procesos y tareas",
    description: "Tareas, proyectos, formularios, automatizaciones y vistas de trabajo.",
    pricingType: "per-user",
    monthlyPrice: 13.49,
    currency: "USD",
    billingCadence: "monthly",
    billingLabel: "por usuario/mes",
    priceNote: "Se usa el precio mensual oficial, no el descuento anual.",
    officialUrl: "https://asana.com/pricing",
    lastVerifiedAt: VERIFIED_AT,
    selectedByDefault: true,
    verificationStatus: "verified",
  },
  {
    id: "clickup-unlimited",
    name: "ClickUp Unlimited",
    category: "Procesos y tareas",
    description: "Gestion de tareas, espacios, objetivos, formularios y seguimiento.",
    pricingType: "per-user",
    monthlyPrice: 10,
    currency: "USD",
    billingCadence: "monthly",
    billingLabel: "por usuario/mes",
    priceNote: "Precio mensual oficial del plan Unlimited.",
    officialUrl: "https://clickup.com/pricing",
    lastVerifiedAt: VERIFIED_AT,
    verificationStatus: "verified",
  },
  {
    id: "trello-premium",
    name: "Trello Premium",
    category: "Procesos y tareas",
    description: "Tableros, vistas, automatizaciones y administracion de equipos.",
    pricingType: "per-user",
    monthlyPrice: 12.5,
    currency: "USD",
    billingCadence: "monthly",
    billingLabel: "por usuario/mes",
    priceNote: "Se usa el precio mensual oficial indicado entre parentesis.",
    officialUrl: "https://trello.com/pricing",
    lastVerifiedAt: VERIFIED_AT,
    verificationStatus: "verified",
  },
  {
    id: "quickbooks-simple-start",
    name: "QuickBooks Online Simple Start",
    category: "Contabilidad",
    description: "Contabilidad en linea, facturas, gastos y reportes financieros basicos.",
    pricingType: "flat",
    monthlyPrice: 38,
    currency: "USD",
    billingCadence: "monthly",
    billingLabel: "precio fijo mensual",
    priceNote: "Se ignora la promocion temporal visible y se toma el precio regular publicado.",
    officialUrl: "https://quickbooks.intuit.com/pricing/",
    lastVerifiedAt: VERIFIED_AT,
    selectedByDefault: true,
    verificationStatus: "verified",
  },
  {
    id: "xero-growing",
    name: "Xero Growing",
    category: "Contabilidad",
    description: "Contabilidad, facturas, conciliacion y reportes para operaciones en crecimiento.",
    pricingType: "flat",
    monthlyPrice: 55,
    currency: "USD",
    billingCadence: "monthly",
    billingLabel: "precio fijo mensual",
    priceNote: "Se usa el precio regular posterior a promocion temporal.",
    officialUrl: "https://www.xero.com/us/pricing-plans/",
    lastVerifiedAt: VERIFIED_AT,
    verificationStatus: "verified",
  },
  {
    id: "zoho-books-standard",
    name: "Zoho Books Standard",
    category: "Contabilidad",
    description: "Libros, impuestos, reportes, proveedores y contabilidad para pequenas empresas.",
    pricingType: "flat",
    monthlyPrice: 20,
    currency: "USD",
    billingCadence: "monthly",
    billingLabel: "precio fijo mensual",
    priceNote: "Precio mensual por organizacion mostrado en la pagina oficial.",
    officialUrl: "https://www.zoho.com/us/books/pricing/",
    lastVerifiedAt: VERIFIED_AT,
    verificationStatus: "verified",
  },
  {
    id: "zoho-inventory-standard",
    name: "Zoho Inventory Standard",
    category: "Inventario",
    description: "Ordenes, usuarios incluidos, ubicaciones y control de inventario independiente.",
    pricingType: "flat",
    monthlyPrice: 29,
    annualPrice: 348,
    currency: "USD",
    billingCadence: "annual",
    billingLabel: "por organizacion/mes, facturado anual",
    priceNote: "Precio anual oficial dividido por mes para estimacion mensual.",
    officialUrl: "https://www.zoho.com/us/inventory/pricing/",
    lastVerifiedAt: VERIFIED_AT,
    selectedByDefault: true,
    verificationStatus: "verified",
  },
  {
    id: "bamboohr-core",
    name: "BambooHR Core",
    category: "Recursos humanos",
    description: "Base de empleados, documentos, flujos de RR. HH. y datos del equipo.",
    pricingType: "per-user",
    monthlyPrice: 10,
    currency: "USD",
    billingCadence: "monthly",
    billingLabel: "por empleado/mes",
    priceNote: "BambooHR publica precio por empleado para empresas de mas de 25 empleados.",
    officialUrl: "https://www.bamboohr.com/pricing/",
    lastVerifiedAt: VERIFIED_AT,
    selectedByDefault: true,
    verificationStatus: "verified",
  },
  {
    id: "shopify-pos-pro",
    name: "Shopify POS Pro",
    category: "Punto de venta",
    description: "POS avanzado por ubicacion con permisos, inventario y reportes de retail.",
    pricingType: "flat",
    monthlyPrice: 89,
    annualPrice: 1068,
    currency: "USD",
    billingCadence: "annual",
    billingLabel: "por ubicacion/mes, facturado anual",
    priceNote: "Estimacion para una ubicacion; no incluye plan Shopify ni transacciones.",
    officialUrl: "https://www.shopify.com/pos/pricing",
    lastVerifiedAt: VERIFIED_AT,
    selectedByDefault: true,
    verificationStatus: "verified",
  },
  {
    id: "freshbooks-plus",
    name: "FreshBooks Plus",
    category: "Facturacion",
    description: "Facturacion, gastos, propuestas y reportes para negocios de servicios.",
    pricingType: "flat",
    monthlyPrice: 43,
    currency: "USD",
    billingCadence: "monthly",
    billingLabel: "precio fijo mensual",
    priceNote: "Se usa el precio regular indicado como Was, no la promocion temporal.",
    officialUrl: "https://www.freshbooks.com/pricing",
    lastVerifiedAt: VERIFIED_AT,
    verificationStatus: "verified",
  },
];

export const SOFTWARE_CATEGORIES = Array.from(
  new Set(EXTERNAL_SOFTWARE_PRICING.map((software) => software.category)),
);
